### ISSUE TITLE
Bug : piétinement + esquive acrobatique

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#126]
Ulti, je remarque qu'avec le refactoring des rolls d'events le script plante également sur une esquive acrobatique d'une attaque avec piétinement. Il est tard, je veux bien regarder demain, mais si tu as une idée, n'hésite pas (car ça fonctionnait avant) : 

`TypeError: Cannot read property 'total' of undefined
TypeError: Cannot read property 'total' of undefined
    at apiscript.js:15632:34
    at checkFinishedOps (eval at <anonymous> (/home/node/d20-api-server/api.js:158:1), <anonymous>:757:7)
    at eval (eval at <anonymous> (/home/node/d20-api-server/api.js:158:1), <anonymous>:837:8)
    at Timeout._onTimeout (/home/node/d20-api-server/node_modules/underscore/underscore.js:825:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

**Comment by Ulty** [comment]
Je sais pourquoi ça plante : testOpposé ne retourne pas un roll, je vais changer ça.
