### ISSUE TITLE
Bug de partie 20/9/21

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#291]
Je pose ça ici en milieu de partie pour pas le perdre

TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
    at synchronisationDesEtats (apiscript.js:37313:23)
    at initTokenMarkers (apiscript.js:37428:5)
    at Array.forEach (<anonymous>)
    at initAllMarkers (apiscript.js:37501:12)
    at eval (eval at <anonymous> (/home/node/d20-api-server/api.js:168:1), <anonymous>:65:16)
    at Object.publish (eval at <anonymous> (/home/node/d20-api-server/api.js:168:1), <anonymous>:70:8)
    at TrackedObj.set (/home/node/d20-api-server/api.js:1071:14)
    at updateLocalCache (/home/node/d20-api-server/api.js:1414:18)
    at /home/node/d20-api-server/api.js:1706:7
    at /home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:560

**Comment by Ulty** [comment]
Merci d'avoir rapporté ça !

**Comment by Far2Casual** [comment]
T'as déjà fixé avant même que j'aie eu le temps de regarder ce qui se passait 😅
